### PR TITLE
Refactor polling/destroy workflow

### PR DESCRIPTION
**Pull request by bmorton**
Currently we only poll for the presence of a unit when we're triggering a destroy after it loads.  We also poll each instance separately, so a 10-instance deploy would result in us hitting Fleet's status endpoint 10 times every second to check on the instance status when we can check them all at the same time.

The reason this work happened is for #36 where we're going to want to trigger more events based on the states of units.  This is the footwork for making that possible.
#### There are a few other things that happen in this PR as a result of the above
- We no longer pass around a bunch of variables about the deploy, we now pass around a Deploy struct
- We now have a `schema` package for starting to contain domain "objects" that are shared across the app
- We have a `clients` package to contain the interfaces of our Fleet and Docker client implementations.  This is to prevent circular dependencies and reduce some duplication.
- We now have a `units` package to contain all the unit-transformation related code.

### CODE REVIEW

**Comment by bmorton** [comment]
I feel terrible that this diff has gotten so massive, but some things were pretty coupled and this detangled a lot of stuff.  Largely I wanted to get rid of [this horrible method](https://github.com/bmorton/deployster/pull/52/files#diff-952808dff09cec311642f818dcb680eeL220) and get it tested better, which it now is in the `poller` package.

@ivanvanderbyl, @bobbytables: would either of you mind reviewing this as best you can?  Also, I know that @ivanvanderbyl has some stuff in flight, so would be good to determine if I should land this after or before his stuff comes in.

**Comment by ivanvanderbyl** [comment]
I like this refactoring a lot. It makes the package much easier to build upon. I'll refactor my in-flight stuff to work with this.

**Comment by ivanvanderbyl** [comment]
With regard to checking if a repository can be downloaded, I've been thinking about whether this solves a real problem or whether the real problem is that we need a better way to tail events from deployster to be notified if a deployment fails.

**Comment by bmorton** [comment]
Yeah, I think better failure notification of some sort would help that problem (and other problems) quite a bit.  It'd be nice to have an expectation that a deploy will reasonably succeed if the deploy is accepted (the version checking stuff), but if we have better failure notification, it'd be less necessary for sure.

**Pull request merged**
