### PR TITLE
Remove references to self and replace with more idiomatic go-way names.

### PR DESCRIPTION
**Pull request by bobbytables**
goimports / fmt everything as well.

### CODE REVIEW

**Comment by bmorton** [comment]
I just added the `.travis.yml` file to master.  If you rebase master, this should run correctly now.

**Comment by bobbytables** [comment]
@bmorton - updated.

**Comment by bmorton** [comment]
I forgot this PR was in flight and I just moved around a bunch of stuff.  Would you mind rebasing against the moved files?  Sorry @bobbytables :(

**Comment by bobbytables** [comment]
Jerk.

**Comment by bobbytables** [comment]
Hold off. Doing a few more I found.

**Comment by bobbytables** [comment]
@bmorton rebased & squashed.

**Comment by bmorton** [comment]
Awesome, thanks!  I'll merge this shortly.  Did you see my other question about the interface check in the mock?  It seems to be gone after the rebase.

**Comment by bobbytables** [comment]
@bmorton - Yeah I didn't know that was generated. What we can do is just make another file for the package that includes those types of checks. That way it won't be overwritten. How's that sound?

**Comment by bobbytables** [comment]
I think it would be valuable to check the generated mocks because if the interface changes, it'll fail and signal you need to regenerate the mocks file too.

**Comment by bmorton** [comment]
Yeah, that sounds good to me.  Once you've got that change in place, we can merge this.

It might still be valuable for the mockery library to add this check when generating the mock.

**Comment by bobbytables** [comment]
@bmorton - This is updated.

**Comment by bmorton** [comment]
Weird that Travis didn't build this.  Gonna manually run the suite and then I'll merge.

**Comment by bmorton** [comment]
Looks good to me!  Thanks for doing this @bobbytables.

**Pull request merged**
